# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements_dev.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

# Command to run tests, e.g. python setup.py test
script: 
  - pytest --cov=photopy
after_success:
  - coveralls
